version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: notes-postgres
    environment:
      POSTGRES_DB: notesapp
      POSTGRES_USER: notesapp_user
      POSTGRES_PASSWORD: cherry2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
